[settings]
idiomatic_version_file_enable_tools = ["python"]

[tasks.install]
alias = "i"
run = "uv sync --locked --group dev"

[tasks.lint]
run = "uv run --no-sync ruff check ."

[tasks.typecheck]
run = "uv run --no-sync ty check ."

[tasks.test]
run = "uv run --no-sync pytest --cov=app --cov-report=term-missing"
